### PR TITLE
Added support for extensions.

### PR DESCRIPTION
**Pull request by J-Cake**
I felt that this could be an interesting addition. I've added support for extensions by using shared libraries. It's not extensive, but its enough to define any action within your OS or DE using these extensions. 

PS. I made some changes to the change desktop animation which I couldn't figure out how to remove, so I've reverted the commit to restore the original animation.

### CODE REVIEW

**Comment by JoseExposito** [comment]
Hi @J-Cake, thanks for the PR!

I've mixed feelings about plugins. On the one hand, it is great to give users/developers flexibility create their own stuff.
On the other hand, why not contribute those changes upstream so everyone, not only your distro/DE users or those who "Googled" the right keywords, can use it?

I tend to prefer the upstream solution, for many reasons:
- First, it benefits all users, not only the plugin users
- Unless you have a great infrastructure, like for example, GNOME has with their extensions, plugins are difficult to find and install
- Plugins hide bugs. If there is a bug upstream, but using plugin X solves it, the bug remains upstream for everyone
- They also create bugs... and I do not have the resources to test a bug when plugin X is installed along side plugin Y after removing Z
- The plugin interface needs to be **very** well thought, because once it's released, it can't change
- In addition to an app, now I have to maintain that interface, and make sure I don't break any plugin, even if only one person is using it... Even more testing

Said that, what's your use case? Maybe we can solve it without creating a whole plugin system.

**Comment by J-Cake** [comment]
Thanks for the feedback, I hadn't thought of the possible negatives like that. The reason I had this idea is because I'd like to add a gesture to control KDE Plasma's activities which other DEs like Gnome or Mate lack anything close to that. Further, I was looking for a way to make the transitions between desktops slide the actual desktop, rather than showing an overlay, which again is platform specific (to my knowledge).
For me, this creates a scenario where adding a feature upstream that is platform dependent while its parent application isn't, is a terrible idea for UX. Hence the notion of extensions.

You mentioned the extra work required in maintaining a plugin interface, which is fair and valid, however, as the project is small-ish, with most of the desirable features existing natively, updates to the interface will rarely be necessary. Plus the nature of the interface relying on C++ developers will mean that issues that do arise can be addressed and/or resolved efficiently. 

I realise this is a somewhat dismissive answer, however in a practical sense (I am an example of this - changed the desktop animation) this works. 

Please let me know your thoughts, I'd love to aid this project in any way I can.

**Comment by JoseExposito** [comment]
Cool, it is possible to integrate Touchégg and KWin without any extra code. 

Touchégg has a daemon (server) client architecture. The daemon, run by systemd as part of the INPUT group, has access to the gestures made by the user and sends them through a Unix socket using D-Bus to the client(s).

You could write you own client and integrate it in KDE. I believe your client should be a KWin plugin to do stuff like switching desktops. I've done that in 2 DEs, so you shouldn't need anything else.

More information and reference implementations:
https://blog.elementary.io/multitouch-gestures-in-elementary-os-6/
https://github.com/JoseExposito/gnome-shell-extension-x11gestures

By the way, Touchégg is only required on X11 because at the moment there is no way to receive multitouch gestures using the "normal" X11 way (Google XInput for more historical info). Fortunately, Wayland has a multitouch protocol.
I believe KDE's Wayland session works quite, so maybe KWin devs are interested on integrating your work directly in the compositor (KWin) instead of requiring a plugin.

**Comment by J-Cake** [comment]
Okay, thanks for the pointers. I'll look into the Wayland solution, as I didn't know that existed. 

Thanks again for taking the time to review my PR. 

J-Cake

**Pull request closed without merging**
