### PR TITLE
Updating dependencies for QT 5.1 to compile on Ubuntu 15.10

### PR DESCRIPTION
**Pull request by chrmod**

### CODE REVIEW

**Comment by chrmod** [comment]
To be honest I have absolutely zero knowledge of QT or modern C++, but that is what I have to do in order to compile touchegg on my system.

**Comment by chrmod** [comment]
Wiki page on how to compile should also be updated https://github.com/JoseExposito/touchegg/wiki/How-to-compile-Touch%C3%A9gg-source-code to match qt5 dependecies

**Comment by Eventide** [comment]
Yeah `utouch` is not needed. I installed it on my LMDE 2.

**Comment by eworm-de** [comment]
Using this for the ArchLinux package in AUR...
https://aur.archlinux.org/packages/touchegg-qt5/

The Qt5 dependency is `qt5-x11extras` for us.

**Comment by JoseExposito** [comment]
Today I released Touchégg v2 :package: 

This version adds cool animations and libinput support.
Check out the project page for more information and a demo:
https://github.com/JoseExposito/touchegg#readme

Thank you very much for your pull request... and sorry for my inactivity :worried:

**Pull request closed without merging**
