### PR TITLE
Use user systemd service instead of starting manually

### PR DESCRIPTION
**Pull request by m-roberts**
I have made several assumptions here, and this is likely to require some changes and proper testing before ready.

~First of all, the existing systemd service currently is set to `WantedBy=multi-user.target`, which is actually not correct, as it requires an X11 display to function. It should be `WantedBy=graphical.target`.~

Note:
it appears as though the version of `systemd` in Debian Buster (at least, this appears to be the case on Raspberry Pi OS) does not handle user services that are `WantedBy=multi-user.target` or `WantedBy=graphical.target`. `systemd` in the Buster Backports repository does work, however.
The "fix" for this (until Bullseye is released) would be to set it to `WantedBy=default.target`, though this will cause the service to fail if the system is not configured to boot to desktop, as this service will mistakenly try to start. I think that this is an acceptable fail case for the ~6 months that it will be necessary. To my knowledge, no other distro will suffer from this issue after Debian updates.

### CODE REVIEW

**Comment by JoseExposito** [comment]
Correct me if I am wrong, but, doesn't the desktop file added to `/etc/xdg/autostart` archive something similar to this PR? Is it not working on your system?

Here is the desktop file:
https://github.com/JoseExposito/touchegg/blob/master/installation/touchegg.desktop

**Comment by JoseExposito** [comment]
I missed this bit:

> First of all, the existing systemd service currently is set to WantedBy=multi-user.target, which is actually not correct, as it requires an X11 display to function. It should be ``WantedBy=graphical.target`.

The current service (the daemon) does not access X11. The client is the one that connects to X11. I think that `multi-user.target` should be fine.

**Comment by m-roberts** [comment]
Good point - I will revert this on the system service

**Comment by JoseExposito** [comment]
Hi, 

I have a question about this. Lets say that user `A` installed Touchégg. A new user, `B`, is created. Does user `B` have to manually start the user service? Or is it enabled and run by default and `B` can opt-out?

Now that I've remove the session manager tags from the desktop file this PR-draft came to mind as systemd is very reliable in case of crash.

**Comment by m-roberts** [comment]
Each user would need to enable it themselves. However, if you are adding a UI to this package in the future for configuration, you could easily add a "run on login" option so that it does not require any terminal commands?

**Comment by JoseExposito** [comment]
In that case, this is a no-go, it will make the installation complicated and break stuff.
Even with the UI, which is going to be optional and I'll distribute it via Flatpak for the updates, it is an unnecessary extra step for the user, and a confusing one.
In addition, it'll break [other integrations](https://blog.elementary.io/multitouch-gestures-in-elementary-os-6/). 

Thanks for your work on this PR, but I can not merge it, sorry.

**Comment by m-roberts** [comment]
I can understand why this would be unacceptable. but it's a bit of a shame that it is required to run for all desktop users on a machine, regardless of whether or not they want it.. Oh well

**Pull request closed without merging**
